[project]
name = "fa-dae2-capstone-gnart"
version = "0.1.0"
description = "Capstone project for FA DAE2"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.18",
    "cartopy>=0.25.0",
    "earthaccess>=0.15.1",
    "harmony-py>=1.0.0",
    "jupyter>=1.1.1",
    "netcdf4>=1.7.2",
    "psycopg>=3.2.10",
    "psycopg2>=2.9.10",
    "pyarrow>=21.0.0",
    "xarray>=2025.9.0",
]
